Repository jitacm/-30DaysDevChallenge-, pull requests merged in 2024-06, with the labels that each got.

#15 30 dyas of c and 30 days of javascript
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  30_days_of_C/C++/Project_1 _Calculator/Readme.md
  30_days_of_C/C++/Project_1 _Calculator/calculator.c
  30_days_of_javascript/Project_2 - TO-do-list/Readme.md
  30_days_of_javascript/Project_2 - TO-do-list/index.html
  30_days_of_javascript/Project_2 - TO-do-list/style.css
  30_days_of_javascript/Project_2 - TO-do-list/todo.js
Labels: 30DayChallenge, JIT ACM

#18 30_days_of _python/ weather_App
  30_days_of_javascript/Project_3 - Pomodoro Clock/Readme.md
  30_days_of_javascript/Project_3 - Pomodoro Clock/index.html
  30_days_of_javascript/Project_3 - Pomodoro Clock/script.js
  30_days_of_javascript/Project_3 - Pomodoro Clock/style.css
  30_days_of_python/Project_2_Weather_App/Readme.md
  30_days_of_python/Project_2_Weather_App/weather.py
Labels: 30DayChallenge, JIT ACM

#26 30DaysOfPython-HangmanProject
  30_days_of_python/Project_4_Hangman Game/Hangman.py
  30_days_of_python/Project_4_Hangman Game/README.md
Labels: 30DayChallenge, JIT ACM

#34 30 DAYS OF JS / RANDOM QUOTES GENERATOR
  30_days_of_javascript/Project_4 - Random Quote Generator/index.html
  30_days_of_javascript/Project_4 - Random Quote Generator/readme.md
  30_days_of_javascript/Project_4 - Random Quote Generator/script.js
  30_days_of_javascript/Project_4 - Random Quote Generator/style.css
Labels: 30DayChallenge, JIT ACM

#27 30DaysOfPython-Image Processing Application
  30_days_of_python/Project_3_Image_Processing_Application/README.md
  30_days_of_python/Project_3_Image_Processing_Application/app.py
  30_days_of_python/project_3 image processing application/index.html
Labels: 30DayChallenge, JIT ACM

#38 30 days of JS/ CountdownTimer
  30_days_of_javascript/Project_5 - Countdown Timer/index.html
  30_days_of_javascript/Project_5 - Countdown Timer/readme.md
Labels: 30DayChallenge, JIT ACM

#41 Project_2_Graph_Representation_Algorithm
  30_days_of_C/C++/Project_2_Graph_Representation_Algorithm/Graph.h
  30_days_of_C/C++/Project_2_Graph_Representation_Algorithm/README.md
  30_days_of_C/C++/Project_2_Graph_Representation_Algorithm/main.cpp
Labels: 30DayChallenge, JIT ACM

#42 Update README.md 30 days of python / img processing readme update
  30_days_of_python/Project_3_Image_Processing_Application/README.md
Labels: documentation, 30DayChallenge, JIT ACM

#43 30daysofC/C++-Project_2_Graph_Representation_Algorithm
  Graph.h
  main.cpp
Labels: bug, 30DayChallenge, JIT ACM

#49 30DaysOfFlutter - Update README.md
  30_days_of_Flutter/all_project/lib/Project2_Qr_Gen/README.md
Labels: documentation, 30DayChallenge, JIT ACM

#51 30DaysOfFluttar - Update README.md of Project03
  30_days_of_Flutter/all_project/lib/Project3_CryptoPrice/README.md
Labels: documentation, 30DayChallenge, JIT ACM

#56 30DaysOfFlutter - Update README.md for Project04
  30_days_of_Flutter/all_project/lib/Project4_Pdf_generation/README.md
Labels: documentation, 30DayChallenge, JIT ACM

#53 MCQTest/30_days_of_C/C++
  30_days_of_C/C++/Project_4_MCQTest/MCQTest.c
  30_days_of_C/C++/Project_4_MCQTest/README.md
Labels: 30DayChallenge, JIT ACM, Under Review

#61 Issue no #61 : Enhancements to Combined Database Maintenance and User Management Script
  30_days_of_Cloud/Project_2_Combined_Database_Maintenance_and_User_Management_Script/README.md
  30_days_of_Cloud/Project_2_Combined_Database_Maintenance_and_User_Management_Script/maintenance_and_users.sh
Labels: 30DayChallenge, JIT ACM

#65 Updating README.md file of Project04 - 30DaysOfFlutter
  30_days_of_Flutter/all_project/lib/Project2_Qr_Gen/README.md
  30_days_of_Flutter/all_project/lib/Project4_Pdf_generation/README.md
Labels: 30DayChallenge, JIT ACM

#66 Web_Crawler_for_Email_Extraction
  30_days_of_python/Project_5_Web_Crawler_for_Email_Extraction/Email_Extractor.py
  30_days_of_python/Project_5_Web_Crawler_for_Email_Extraction/README.md
  30_days_of_python/Project_5_Web_Crawler_for_Email_Extraction/requirements.txt
Labels: 30DayChallenge, JIT ACM

#64 Rock_Paper_scissors.30_days_of_C/C++
  30_days_of_C/C++/Project_5_Rock_Paper_Sicssor/README.md
  30_days_of_C/C++/Project_5_Rock_Paper_Sicssor/RockPaperScissor.cpp
Labels: 30DayChallenge, JIT ACM, Under Review

#72 Update README.md for Project 05 - 30DaysOfFlutter
  30_days_of_Flutter/all_project/lib/Project5_Weather_App/README.md
Labels: 30DayChallenge, JIT ACM

#75 CNN model integrated_Mamdani Fuzzy Inference System
  30_days_of_python/Project_6_CNN_With_Mamdani/Cnn_Mamdani.py
  30_days_of_python/Project_6_CNN_With_Mamdani/README.md
Labels: 30DayChallenge, JIT ACM

#78 stack/30_days_of_python
  30_days_of_python/Project_7_stack/README.md
  30_days_of_python/Project_7_stack/Stack.py
Labels: 30DayChallenge, JIT ACM

#80 Weather App / javascript Project
  30_days_of_javascript/Project_6 - Weather App/index.html
  30_days_of_javascript/Project_6 - Weather App/readme.md
  30_days_of_javascript/Project_6 - Weather App/script.js
  30_days_of_javascript/Project_6 - Weather App/style.css
Labels: 30DayChallenge, JIT ACM

#82 Image Slider / javascript project
  30_days_of_javascript/Project_8 - Image Slider/index.html
  30_days_of_javascript/Project_8 - Image Slider/readme.md
  30_days_of_javascript/Project_8 - Image Slider/script.js
  30_days_of_javascript/Project_8 - Image Slider/style.css
Labels: 30DayChallenge, JIT ACM

#83 Currency Converter - Quiz App / javascript project
  30_days_of_javascript/Project_10 - Quiz App/index.html
  30_days_of_javascript/Project_10 - Quiz App/readme.md
  30_days_of_javascript/Project_10 - Quiz App/script.js
  30_days_of_javascript/Project_10 - Quiz App/style.css
  30_days_of_javascript/Project_9 - Currency Converter/index.html
  30_days_of_javascript/Project_9 - Currency Converter/readme.md
  30_days_of_javascript/Project_9 - Currency Converter/script.js
  30_days_of_javascript/Project_9 - Currency Converter/style.css
Labels: 30DayChallenge, JIT ACM

#84 Quiz App / javascript project
  30_days_of_javascript/Project_10 - Quiz App/index.html
  30_days_of_javascript/Project_10 - Quiz App/readme.md
  30_days_of_javascript/Project_10 - Quiz App/script.js
  30_days_of_javascript/Project_10 - Quiz App/style.css
Labels: 30DayChallenge, JIT ACM

#85 Palindrome Checker / JS project
  30_days_of_javascript/Project_11- Palindrome Checker/index.html
  30_days_of_javascript/Project_11- Palindrome Checker/readme.md
  30_days_of_javascript/Project_11- Palindrome Checker/script.js
  30_days_of_javascript/Project_11- Palindrome Checker/style.css
Labels: 30DayChallenge, JIT ACM

#86 Tip Calculator / JS Projects
  30_days_of_javascript/Project_11- Palindrome Checker copy/index.html
  30_days_of_javascript/Project_11- Palindrome Checker copy/readme.md
  30_days_of_javascript/Project_11- Palindrome Checker copy/script.js
  30_days_of_javascript/Project_11- Palindrome Checker copy/style.css
Labels: 30DayChallenge, JIT ACM

#89 Added JS Project 16 , 17
  30_days_of_javascript/Project_16- Unit Converter/index.html
  30_days_of_javascript/Project_16- Unit Converter/readme.md
  30_days_of_javascript/Project_16- Unit Converter/script.js
  30_days_of_javascript/Project_16- Unit Converter/style.css
  30_days_of_javascript/Project_17- Expense Traker/index.html
  30_days_of_javascript/Project_17- Expense Traker/readme.md
  30_days_of_javascript/Project_17- Expense Traker/script.js
  30_days_of_javascript/Project_17- Expense Traker/style.css
Labels: 30DayChallenge, JIT ACM

#90 Python Projects Added / 30days of Python
  30_days_of_python/Project_10_Currency_converter/Currency.py
  30_days_of_python/Project_10_Currency_converter/Readme.md
  30_days_of_python/Project_11_Simple_chat_app/Chat app.py
  30_days_of_python/Project_11_Simple_chat_app/Readme.md
  30_days_of_python/Project_12_Expense_Tracker/Expense.py
  30_days_of_python/Project_12_Expense_Tracker/Readme.md
  30_days_of_python/Project_13_Personal_blog/Personal Blog.md
  30_days_of_python/Project_13_Personal_blog/Personal blog
  30_days_of_python/Project_14_Image_Recognition/Face.py
  30_days_of_python/Project_14_Image_Recognition/Readme.md
  30_days_of_python/Project_15_Stock_price_analyzer/Analyzer.py
  30_days_of_python/Project_15_Stock_price_analyzer/Readme.md
  30_days_of_python/Project_16__BMI_calculator/BMI.py
  30_days_of_python/Project_16__BMI_calculator/Readme.md
  30_days_of_python/Project_17_Password_Generator/Password.py
  30_days_of_python/Project_17_Password_Generator/Readme.md
  30_days_of_python/Project_18_QR_Code_Generator/QR.py
  30_days_of_python/Project_18_QR_Code_Generator/Readme.md
  30_days_of_python/Project_20_Alarm_clock/Alarm.py
  30_days_of_python/Project_20_Alarm_clock/Readme.md
  30_days_of_python/Project_21_Contact_Book/Contacts.py
  30_days_of_python/Project_21_Contact_Book/Readme.md
  30_days_of_python/Project_22_Library_Management_system/Library.py
  30_days_of_python/Project_22_Library_Management_system/Readme.md
  30_days_of_python/Project_23_minisweeper/Readme.md
  30_days_of_python/Project_23_minisweeper/game.py
  30_days_of_python/Project_24_Number_to_word/Converter.py
  30_days_of_python/Project_24_Number_to_word/Readme.md
  30_days_of_python/Project_25_URL_shortner/Readme.md
  30_days_of_python/Project_25_URL_shortner/Shrink.py
  30_days_of_python/Project_26_Prime_Number_checker/Prime.py
  30_days_of_python/Project_26_Prime_Number_checker/Readme.md
  30_days_of_python/Project_27_Age_calculator/Age.py
  30_days_of_python/Project_27_Age_calculator/Readme.md
  30_days_of_python/Project_8_Guess_the_number/Readme.md
  30_days_of_python/Project_8_Guess_the_number/guess the number.py
  30_days_of_python/Project_9_To_do_list/Readme.md
  30_days_of_python/Project_9_To_do_list/To do list.py
Labels: 30DayChallenge, JIT ACM

#92 Geological Map Generator & Data Visualization Software / 30 days of Python
  30_days_of_python/Project_29_Geological_Map_Gennerator/README.md
  30_days_of_python/Project_29_Geological_Map_Gennerator/app.py
  30_days_of_python/Project_29_Geological_Map_Gennerator/assets/Screenshot 2024-06-26 210204.png
  30_days_of_python/Project_29_Geological_Map_Gennerator/assets/Screenshot 2024-06-26 210220.png
  30_days_of_python/Project_29_Geological_Map_Gennerator/data/example_data.dbf
  30_days_of_python/Project_29_Geological_Map_Gennerator/data/example_data.prj
  30_days_of_python/Project_29_Geological_Map_Gennerator/data/example_data.shp
  30_days_of_python/Project_29_Geological_Map_Gennerator/data/example_data.shx
  30_days_of_python/Project_30_Data_Visualization_Software/README.md
  30_days_of_python/Project_30_Data_Visualization_Software/app.py
Labels: 30DayChallenge, JIT ACM

#94 Update README.md
  30_days_of_Flutter/all_project/lib/Project6_Bmi_Calculartor/README.md
Labels: 30DayChallenge, JIT ACM

#96 TicTacToe/30_days_of_C/C++
  30_days_of_C/C++/Project_6_TicTacToe/README.md
  30_days_of_C/C++/Project_6_TicTacToe/TicTacToe.c
Labels: 30DayChallenge, JIT ACM

#98 Temperature_converter/30_days_of_C
  30_days_of_C/C++/Project_10_EmployeManagementSystem/EmployeManagementSystem.c
  30_days_of_C/C++/Project_10_EmployeManagementSystem/README.md
  30_days_of_C/C++/Project_11_LibraryManagementSystem/LibraryManagementSystem.c
  30_days_of_C/C++/Project_11_LibraryManagementSystem/README.md
  30_days_of_C/C++/Project_7_Temperature_Converter/README.md
  30_days_of_C/C++/Project_7_Temperature_Converter/Temperature_converter.c
  30_days_of_C/C++/Project_8_ContactManagementSystem/Contact_management_system.c
  30_days_of_C/C++/Project_8_ContactManagementSystem/README.md
  30_days_of_C/C++/Project_9_Hang_man_Game/HangManGame.c
  30_days_of_C/C++/Project_9_Hang_man_Game/README.md
Labels: 30DayChallenge, JIT ACM, C/ C++

#103 Typing Speed Test / JS Projects -18
  30_days_of_javascript/Project_18- Typing Speed Test/index.html
  30_days_of_javascript/Project_18- Typing Speed Test/readme.md
  30_days_of_javascript/Project_18- Typing Speed Test/script.js
  30_days_of_javascript/Project_18- Typing Speed Test/style.css
  30_days_of_javascript/Project_19- Password Generator/index.html
  30_days_of_javascript/Project_19- Password Generator/readme.md
  30_days_of_javascript/Project_19- Password Generator/script.js
  30_days_of_javascript/Project_19- Password Generator/style.css
  30_days_of_javascript/Project_20- Grocery List App/index.html
  30_days_of_javascript/Project_20- Grocery List App/readme.md
  30_days_of_javascript/Project_20- Grocery List App/script.js
  30_days_of_javascript/Project_20- Grocery List App/style.css
  30_days_of_javascript/Project_21-Markdown Previewer/index.html
  30_days_of_javascript/Project_21-Markdown Previewer/readme.md
  30_days_of_javascript/Project_21-Markdown Previewer/script.js
  30_days_of_javascript/Project_21-Markdown Previewer/style.css
  30_days_of_javascript/Project_22- Weather Dashboard/index.html
  30_days_of_javascript/Project_22- Weather Dashboard/readme.md
  30_days_of_javascript/Project_22- Weather Dashboard/script.js
  30_days_of_javascript/Project_22- Weather Dashboard/style.css
  30_days_of_javascript/Project_23- Random Color Generator/index.html
  30_days_of_javascript/Project_23- Random Color Generator/readme.md
  30_days_of_javascript/Project_23- Random Color Generator/script.js
  30_days_of_javascript/Project_23- Random Color Generator/style.css
  30_days_of_javascript/Project_24- Recipe App/index.html
  30_days_of_javascript/Project_24- Recipe App/readme.md
  30_days_of_javascript/Project_24- Recipe App/script.js
  30_days_of_javascript/Project_24- Recipe App/style.css
  30_days_of_javascript/Project_25- Notes App/index.html
  30_days_of_javascript/Project_25- Notes App/readme.md
  30_days_of_javascript/Project_25- Notes App/script.js
  30_days_of_javascript/Project_25- Notes App/style.css
  30_days_of_javascript/Project_26- Movie Search App/index.html
  30_days_of_javascript/Project_26- Movie Search App/readme.md
  30_days_of_javascript/Project_26- Movie Search App/script.js
  30_days_of_javascript/Project_26- Movie Search App/style.css
  30_days_of_javascript/Project_27- Weather Forecast Chart/index.html
  30_days_of_javascript/Project_27- Weather Forecast Chart/readme.md
  30_days_of_javascript/Project_27- Weather Forecast Chart/script.js
  30_days_of_javascript/Project_27- Weather Forecast Chart/style.css
  30_days_of_javascript/Project_28- Kanban Board/index.html
  30_days_of_javascript/Project_28- Kanban Board/readme.md
  30_days_of_javascript/Project_28- Kanban Board/script.js
  30_days_of_javascript/Project_28- Kanban Board/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#104 password generator tool - project 19 / JS
  30_days_of_javascript/Project_19- Password Generator/index.html
  30_days_of_javascript/Project_19- Password Generator/readme.md
  30_days_of_javascript/Project_19- Password Generator/script.js
  30_days_of_javascript/Project_19- Password Generator/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#105 Grocery List App project -20 /JS
  30_days_of_javascript/Project_20- Grocery List App/index.html
  30_days_of_javascript/Project_20- Grocery List App/readme.md
  30_days_of_javascript/Project_20- Grocery List App/script.js
  30_days_of_javascript/Project_20- Grocery List App/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#106 Markdown Previewer -21 /JS
  30_days_of_javascript/Project_21-Markdown Previewer/index.html
  30_days_of_javascript/Project_21-Markdown Previewer/readme.md
  30_days_of_javascript/Project_21-Markdown Previewer/script.js
  30_days_of_javascript/Project_21-Markdown Previewer/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#107 JS/ project -22, 23
  30_days_of_javascript/Project_22- Weather Dashboard/index.html
  30_days_of_javascript/Project_22- Weather Dashboard/readme.md
  30_days_of_javascript/Project_22- Weather Dashboard/script.js
  30_days_of_javascript/Project_22- Weather Dashboard/style.css
  30_days_of_javascript/Project_23- Random Color Generator/index.html
  30_days_of_javascript/Project_23- Random Color Generator/readme.md
  30_days_of_javascript/Project_23- Random Color Generator/script.js
  30_days_of_javascript/Project_23- Random Color Generator/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#108 JS project -24, 25, 26 /JS
  30_days_of_javascript/Project_24- Recipe App/index.html
  30_days_of_javascript/Project_24- Recipe App/readme.md
  30_days_of_javascript/Project_24- Recipe App/script.js
  30_days_of_javascript/Project_24- Recipe App/style.css
  30_days_of_javascript/Project_25- Notes App/index.html
  30_days_of_javascript/Project_25- Notes App/readme.md
  30_days_of_javascript/Project_25- Notes App/script.js
  30_days_of_javascript/Project_25- Notes App/style.css
  30_days_of_javascript/Project_26- Movie Search App/index.html
  30_days_of_javascript/Project_26- Movie Search App/readme.md
  30_days_of_javascript/Project_26- Movie Search App/script.js
  30_days_of_javascript/Project_26- Movie Search App/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#109 project added -27.28
  30_days_of_javascript/Project_27- Weather Forecast Chart/index.html
  30_days_of_javascript/Project_27- Weather Forecast Chart/readme.md
  30_days_of_javascript/Project_27- Weather Forecast Chart/script.js
  30_days_of_javascript/Project_27- Weather Forecast Chart/style.css
  30_days_of_javascript/Project_28- Kanban Board/index.html
  30_days_of_javascript/Project_28- Kanban Board/readme.md
  30_days_of_javascript/Project_28- Kanban Board/script.js
  30_days_of_javascript/Project_28- Kanban Board/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#110 real-time chat application -29 /JS
  30_days_of_javascript/Project_29- Real-Time Chat App/index.html
  30_days_of_javascript/Project_29- Real-Time Chat App/readme.md
  30_days_of_javascript/Project_29- Real-Time Chat App/script.js
  30_days_of_javascript/Project_29- Real-Time Chat App/server.js
  30_days_of_javascript/Project_29- Real-Time Chat App/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#111 JS project -30 /JS
  30_days_of_javascript/Project_30- social media dashboard/index.html
  30_days_of_javascript/Project_30- social media dashboard/readme.md
  30_days_of_javascript/Project_30- social media dashboard/script.js
  30_days_of_javascript/Project_30- social media dashboard/style.css
Labels: 30DayChallenge, JIT ACM, JavaScript

#112 30 days of_Arduino/ arduino Project Added 1-20
  30_days_of_Arduino/Automatic Plant Watering System/app.cpp
  30_days_of_Arduino/Automatic Plant Watering System/readme.md
  30_days_of_Arduino/Bluetooth Controlled LED/app.cpp
  30_days_of_Arduino/Bluetooth Controlled LED/readme.md
  30_days_of_Arduino/Capacitive Touch Lamp/app.cpp
  30_days_of_Arduino/Capacitive Touch Lamp/readme.md
  30_days_of_Arduino/Digital Dice/app.cpp
  30_days_of_Arduino/Digital Dice/readme.md
  30_days_of_Arduino/Digital Stopwatch/app.cpp
  30_days_of_Arduino/Digital Stopwatch/readme.md
  30_days_of_Arduino/Digital_Thermometer/app.cpp
  30_days_of_Arduino/Digital_Thermometer/readme.md
  30_days_of_Arduino/Gesture Controlled Robot/app.cpp
  30_days_of_Arduino/Gesture Controlled Robot/readme.md
  30_days_of_Arduino/Heart Rate Monitor/app.cpp
  30_days_of_Arduino/Heart Rate Monitor/readme.md
  30_days_of_Arduino/Internet of Things (IoT) Weather Station/app.cpp
  30_days_of_Arduino/Internet of Things (IoT) Weather Station/readme.md
  30_days_of_Arduino/LED Blink/1/app.cpp
  30_days_of_Arduino/LED Blink/readme.md
  30_days_of_Arduino/Light Follower Robot/app.cpp
  30_days_of_Arduino/Light Follower Robot/readme.md
  30_days_of_Arduino/Motion Detector/app.cpp
  30_days_of_Arduino/Motion Detector/readme.md
  30_days_of_Arduino/Obstacle Avoidance Robot/app.cpp
  30_days_of_Arduino/Obstacle Avoidance Robot/readme.md
  30_days_of_Arduino/Password Protected Door Lock/app.cpp
  30_days_of_Arduino/Password Protected Door Lock/readme.md
  30_days_of_Arduino/Remote Controlled Car/app.cpp
  30_days_of_Arduino/Remote Controlled Car/readme.md
  30_days_of_Arduino/Simple Alarm System/app.cpp
  30_days_of_Arduino/Simple Alarm System/readme.md
  30_days_of_Arduino/Simple Servo Motor Control/app.cpp
  30_days_of_Arduino/Simple Servo Motor Control/readme.md
  30_days_of_Arduino/Temperature and Humidity Monitor/app.cpp
  30_days_of_Arduino/Temperature and Humidity Monitor/readme.md
  30_days_of_Arduino/Traffic_Light_controller/app.cpp
  30_days_of_Arduino/Traffic_Light_controller/readme.md
  30_days_of_Arduino/Weather Station/app.cpp
  30_days_of_Arduino/Weather Station/readme.md
Labels: 30DayChallenge, JIT ACM, Arduino
