Repository jitacm/-30DaysDevChallenge-, pull requests merged in 2024-07, with the labels that each got.

#114 Projects from 12 to 16/30_days_of_C/C++
  30_days_of_C/C++/Project_12_Voting_System/README.md
  30_days_of_C/C++/Project_12_Voting_System/VotingSystem.c
  30_days_of_C/C++/Project_13_ATM_System/ATMSystem.c
  30_days_of_C/C++/Project_13_ATM_System/README.md
  30_days_of_C/C++/Project_14_Train_Reservation/README.md
  30_days_of_C/C++/Project_14_Train_Reservation/TrainReservation.c
  30_days_of_C/C++/Project_15_Digital_clock/DigitalClock.c
  30_days_of_C/C++/Project_15_Digital_clock/README.md
  30_days_of_C/C++/Project_16_College_admission_system/CollegeAdmission.c
  30_days_of_C/C++/Project_16_College_admission_system/README.md
Labels: 30DayChallenge, JIT ACM, C/ C++

#118 Project_19_ExpenseTracker - 30DaysOfPython
  30_days_of_python/Project_19_ExpenseTracker/ExpenseTracker.py
  30_days_of_python/Project_19_ExpenseTracker/README.MD
Labels: 30DayChallenge, JIT ACM, Python

#102 Simultaneous Equations Solver
  .vscode/launch.json
  30_days_of_java/Project_2_Simultaneous_Equations_Solver/README.md
  30_days_of_java/Project_2_Simultaneous_Equations_Solver/SimultaneousEquationsSolver.java
Labels: 30DayChallenge, JIT ACM, Java

#117 Bus_Reservation/30_days_of_C/C++
  30_days_of_C/C++/Project_17_Bus_Reservation/Bus_Reservation.cpp
  30_days_of_C/C++/Project_17_Bus_Reservation/README.md
  30_days_of_C/C++/Project_18_Student_Record/README.md
  30_days_of_C/C++/Project_18_Student_Record/Student_Record.cpp
Labels: 30DayChallenge, JIT ACM, C/ C++

#121 Student_Record
  30_days_of_C/C++/Project_18_Student_Record/README.md
  30_days_of_C/C++/Project_19_Bank_Management_System/Bank_Management_System.cpp
  30_days_of_C/C++/Project_19_Bank_Management_System/README.md
Labels: 30DayChallenge, JIT ACM, C/ C++

#131 Grocery_Billing_System/30_days_of_C
  .vscode/launch.json
  30_days_of_C/C++/Project_23_Grocery_Billing_System/Grocery_Billing.c
  30_days_of_C/C++/Project_23_Grocery_Billing_System/README.md
  30_days_of_C/C++/Project_24_Job_Portal/Job_Portal.c
  30_days_of_C/C++/Project_24_Job_Portal/README.md
  30_days_of_C/C++/Project_25_Virtual_Classroom/README.md
  30_days_of_C/C++/Project_25_Virtual_Classroom/Virtual_Classroom.cpp
Labels: 30DayChallenge, JIT ACM, C/ C++

#129 Text_Management_System_30_days_of_C/C++
  30_days_of_C/C++/Project_22_Text_Management_System/README.md
  30_days_of_C/C++/Project_22_Text_Management_System/Text_Management_System.cpp
  30_days_of_C/C++/Project_26_Inventory_Management_System/Inventory_Management_System.cpp
  30_days_of_C/C++/Project_26_Inventory_Management_System/README.md
  30_days_of_C/C++/Project_27_Expense_Tracker/Expense_Tracker.cpp
  30_days_of_C/C++/Project_27_Expense_Tracker/README.md
  30_days_of_C/Project_28_AI-Based_Personal_Assistant/AI-Based_Personal_Assistant.cpp
  30_days_of_C/Project_28_AI-Based_Personal_Assistant/README.md
Labels: 30DayChallenge, JIT ACM, C/ C++

#146 Blog Application/30_Days_of_JavaScript#146
  30_days_of_javascript/Blog Application/app.js
  30_days_of_javascript/Blog Application/index.html
  30_days_of_javascript/Blog Application/readme.md
  30_days_of_javascript/Blog Application/styles.css
Labels: 30DayChallenge, JIT ACM, JavaScript, LEVEL-2, Change Needed !

#163 RPN_Calculator/30_days_of_javascript #155
  30_days_of_javascript/Project_1 - RPN_Calculator/calculator.js
Labels: 30DayChallenge, JIT ACM, JavaScript, LEVEL-1

#165 TO-do-list/30_days_of_javascript #157
  30_days_of_javascript/Project_2 - TO-do-list/Readme.md
  30_days_of_javascript/Project_2 - TO-do-list/style.css
  30_days_of_javascript/Project_2 - TO-do-list/todo.js
Labels: 30DayChallenge, JIT ACM, JavaScript, LEVEL-1

#186 Implement OTP Generator / 30_Days_Of_Java #180
  30_days_of_java/project_5_OTP Generator/LICENSE
  30_days_of_java/project_5_OTP Generator/OtpGenerator.java
  30_days_of_java/project_5_OTP Generator/OtpGeneratorTest.java
  30_days_of_java/project_5_OTP Generator/OtpValidator.java
  30_days_of_java/project_5_OTP Generator/OtpValidatorTest.java
  30_days_of_java/project_5_OTP Generator/README.md
  30_days_of_java/project_5_OTP Generator/launch.json
  30_days_of_java/project_5_OTP Generator/pom.xml
Labels: LEVEL-2
